name: Pr Labeler Action CI

on:
  push:
    branches:
      - main
    tags:
      - '*'

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '*'
          check-latest: true

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Run Linter
        run: yarn lint

      - name: Check Format
        run: yarn format-check

      - name: Run Build
        run: yarn build
